# Generated by Django 3.2 on 2023-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.EmailField(max_length=254, verbose_name='Пороль'),
        ),
    ]
